name: Master CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build + Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ruby Install
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle Install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Rspec
        run: |
          bundle exec rspec -f doc

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure GitHub Package Registry
        run: |
          mkdir -p ~/.gem
          touch ~/.gem/credentials
          chmod 600 ~/.gem/credentials
          echo ":github: Bearer ${PACKAGE_TOKEN}" >> ~/.gem/credentials
        env:
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - uses: actions/checkout@v2

      - name: Push gem to GitHub
        run: |
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/mythcoders *.gem
