name: Master CI

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build + Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ruby Install
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"

      - name: Bundle Install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Rspec
        run: |
          bundle exec rspec -f doc

      - name: Publish
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: Bearer ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/mythcoders *.gem
        env:
          GEM_HOST_API_KEY: ${{secrets.GITHUB_TOKEN}}
          OWNER: mythcoders

  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: Bearer ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/mythcoders *.gem
        env:
          GEM_HOST_API_KEY: ${{secrets.GITHUB_TOKEN}}
          OWNER: mythcoders
