name: PR CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build + Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ruby Install
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle Install
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Rspec
        run: |
          bundle exec rspec -f doc
